[build]
  command = "npm run generate"
  publish = ".output/public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

# Enable Identity service
[context.production]
  command = "npm run generate"

# Git Gateway settings
[template]
  incoming-hooks = ["Git Gateway"]
